# to create new miniconda/anaconda environment:
## conda env create -f environment.yml; conda activate qpowergrid
name: qpgrid
channels:
  - defaults
  - conda-forge
dependencies:
# classiq only runs up to 3.11, not 3.12
# so we only install python up to 3.11
  - python==3.11 
  - ipykernel  # for jupyter notebooks
  - numpy
# PANDAPOWER + REQUIREMENTS
  - pandapower
  - pytest
  - scipy
  - pandas
  - packaging
  - tqdm
  - deepdiff
  - psycopg2  # PostgreSQL adapter
  - networkx  # for general graphs
  - numba     # improves performance
  - ortools   # google mixed-integer programming optimization tools
### pandapower.plotting
  - python-igraph
  - geopandas
  - geojson
# PLOTTING
  - matplotlib
  - python-igraph  # plotting
  - plotly
  - nbformat       # plotly in ipynb
# QUANTUM
#  - pip  # to install classiq
#  - pip:
#    - classiq  
  # or qiskit:
#  - qiskit-terra  # conda-forge::
#  - dwave-ocean-sdk
# OTHERS
#  - pyvis   # conda-forge::
#  - pytorch  # for GNN
  # to install classiq: